using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SerializableGenerator;

[Generator]
public class HelloSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static initContext =>
        {
            // 名前の競合でエラーが起こることが多々あるので、明示的にglobal::からクラス名を書いておく
            var source = """
                         // <auto-generated/>

                         namespace HelloGenerator
                         {
                              [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
                              internal sealed class GenerateHelloAttribute : global::System.Attribute
                              {
                              }
                         }
                         """;

            // 第一引数に渡すhintNameはGeneratorごとに一意である必要がある
            initContext.AddSource("GenerateHelloAttribute.g.cs", source);
        });

        // 名前で指定された属性に対するIncrementalValuesProviderを作成する
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            // 対象の属性のフルネーム
            "HelloGenerator.GenerateHelloAttribute",
            // predicate, 追加でフィルタリングを行いたければこのラムダ式で
            static (node, cancellationToken) => true,
            // transform, GeneratorAttributeSyntaxContextから必要な情報に加工する(今回はcontextをそのまま利用する)
            static (context, cancellationToken) => context
        );
        context.RegisterSourceOutput(provider, Emit);
    }

    private static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext attributeContext)
    {
        // GeneratorAttributeSyntaxContextから対象のSymbolとSyntaxNodeを取得できる
        var typeSymbol = (INamedTypeSymbol)attributeContext.TargetSymbol;
        var typeNode = (TypeDeclarationSyntax)attributeContext.TargetNode;

        // namespace部分 (UnityのC# 9.0に対応する場合はfile scoped namespaceを使わない)
        var nsBegin = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"namespace {typeSymbol.ContainingNamespace} {{";
        var nsEnd = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : "}";

        // 型をファイル名として利用するためのエスケープ処理
        var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_");

        // 生成コードを作成
        // auto-generatedタグや警告の抑止はテンプレ
        const string sourceCode = """
                                  // <auto-generated/>

                                  #nullable enable
                                  #pragma warning disable CS8600
                                  #pragma warning disable CS8601
                                  #pragma warning disable CS8602
                                  #pragma warning disable CS8603
                                  #pragma warning disable CS8604
                                  """;
        using var sourceStream = new StringWriter();
        using var codeWriter = new IndentedTextWriter(sourceStream);

        codeWriter.WriteLine(sourceCode);
        codeWriter.WriteLine(nsBegin);
        codeWriter.Indent++;
        
        codeWriter.WriteLine($"partial class {typeSymbol.Name}");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;
        
        codeWriter.WriteLine("public void Hello()");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;
        
        codeWriter.WriteLine($"global::System.Console.WriteLine(\"Hello, this is {typeSymbol.Name}!\");");
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");

        codeWriter.Indent--;
        codeWriter.WriteLine(nsEnd);

        var sourceText = SourceText.From(sourceStream.ToString(), Encoding.UTF8);
        context.AddSource($"{fullType}.Hello.g.cs", sourceText);
    }
}