// <auto-generated/>

using System.Globalization;

namespace SerializableGenerator
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class SerdeTypeAttribute : global::System.Attribute { }
}