using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SerializableGenerator;

[Generator]
public class SerdeTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeList = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SerializableGenerator." + k_AttrName,
                static (node, _) => node.GetType().IsAssignableFrom(typeof(StructDeclarationSyntax)) ||
                                    node.GetType().IsAssignableFrom(typeof(ClassDeclarationSyntax)) ||
                                    node.GetType().IsAssignableFrom(typeof(RecordDeclarationSyntax)),
                static (ctx, _) => ctx);

        context.RegisterSourceOutput(typeList, Generate);
        context.RegisterPostInitializationOutput(static ctx => { ctx.AddSource(k_AttrName + ".g.cs", k_AttrImpl); });
    }

    private static void Generate(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        if (source.TargetSymbol is not INamedTypeSymbol symbol) return;

        var memberList = GetFields(symbol);
        var attribute = symbol
            .GetAttributes()
            .FirstOrDefault(x =>
                x.AttributeClass?.ToDisplayString() == "SerializableGenerator.SerdeTypeAttribute"
            );

        if (attribute is null)
        {
            return;
        }

        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : symbol.ContainingNamespace.ToDisplayString();
        var originalName = symbol.Name;
        var generatedName = k_GenTypePrefix + originalName;
        var originalTypeName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var useHelper = symbol.DeclaringSyntaxReferences
            .Any(reference =>
                reference.GetSyntax() is TypeDeclarationSyntax declaration &&
                declaration.Modifiers.Any(SyntaxKind.PartialKeyword)
            );
        var constructor = symbol
            .InstanceConstructors
            .Where(candidate => IsAccessible(candidate, useHelper))
            .OrderBy(candidate => candidate.Parameters.Length)
            .FirstOrDefault(candidate =>
                candidate.Parameters
                    .All(parameter =>
                        parameter.RefKind == RefKind.None &&
                        memberList.Any(member => MatchesParameter(member, parameter)
                        )) &&
                memberList.All(member =>
                    CanAssign(member.Symbol, useHelper) ||
                    candidate.Parameters.Any(parameter => MatchesParameter(member, parameter)))
            );

        if (symbol.IsAbstract || symbol.Arity != 0 || symbol.ContainingType != null ||
            constructor == null || memberList.Any(member => member.VariableName == "ToOriginal"))
        {
            context.ReportDiagnostic(Diagnostic.Create(s_ConversionError,
                symbol.Locations.FirstOrDefault(), originalTypeName));
            return;
        }

        if (HasValueCycle(symbol, new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default)))
        {
            context.ReportDiagnostic(Diagnostic.Create(s_RecursiveLayoutError,
                symbol.Locations.FirstOrDefault(), originalTypeName));
            return;
        }

        foreach (var member in memberList)
        {
            if (!TryGetSerializedType(member.Type, out _))
            {
                context.ReportDiagnostic(Diagnostic.Create(s_UnsupportedMemberError,
                    member.Symbol.Locations.FirstOrDefault(), member.VariableName, member.Type.ToDisplayString()));
                return;
            }
        }

        var sourceCode = new StringWriter();
        var code = new IndentedTextWriter(sourceCode);

        code.WriteLine("// <auto-generated />");
        code.WriteLine("#nullable enable");
        code.WriteLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            code.WriteLine($"namespace {namespaceName};");
            code.WriteLine();
        }

        code.WriteLine($"[{typeof(SerializableAttribute).Namespace}.Serializable]");
        code.WriteLine($"public struct {generatedName}");
        code.WriteLine("{");
        code.Indent++;

        foreach (var member in memberList)
        {
            code.WriteLine($"public {member.TypeName} @{member.VariableName};");
        }

        code.WriteLine();
        code.WriteLine($"public {originalTypeName} ToOriginal()");
        code.WriteLine("{");
        code.Indent++;
        if (useHelper)
            code.WriteLine($"return {originalTypeName}.__FromSerde(this);");
        else
            WriteConversion(code, originalTypeName, constructor, memberList, "this");
        code.Indent--;
        code.WriteLine("}");

        code.Indent--;
        code.WriteLine("}");

        if (useHelper)
        {
            var kind = symbol.IsRecord
                ? (symbol.TypeKind == TypeKind.Struct ? "record struct" : "record class")
                : (symbol.TypeKind == TypeKind.Struct ? "struct" : "class");
            code.WriteLine();
            code.WriteLine($"partial {kind} @{originalName}");
            code.WriteLine("{");
            code.Indent++;
            code.WriteLine($"internal static {originalTypeName} __FromSerde({generatedName} value)");
            code.WriteLine("{");
            code.Indent++;
            WriteConversion(code, originalTypeName, constructor, memberList, "value");
            code.Indent--;
            code.WriteLine("}");
            code.Indent--;
            code.WriteLine("}");
        }

        context.AddSource($"{namespaceName}.{generatedName}.g.cs", sourceCode.ToString());
    }

    private static bool IsAccessible(ISymbol symbol, bool withinOriginalType) =>
        withinOriginalType || symbol.DeclaredAccessibility == Accessibility.Public ||
        symbol.DeclaredAccessibility == Accessibility.Internal ||
        symbol.DeclaredAccessibility == Accessibility.ProtectedOrInternal;

    private static bool CanAssign(ISymbol symbol, bool withinOriginalType) => symbol switch
    {
        IFieldSymbol field => !field.IsReadOnly && IsAccessible(field, withinOriginalType),
        IPropertySymbol property => property.SetMethod != null &&
                                    IsAccessible(property.SetMethod, withinOriginalType),
        _ => false
    };

    private static bool MatchesParameter(FieldPair member, IParameterSymbol parameter) =>
        string.Equals(member.VariableName, parameter.Name, StringComparison.OrdinalIgnoreCase) &&
        SymbolEqualityComparer.Default.Equals(member.Type, parameter.Type);

    private static void WriteConversion(IndentedTextWriter code, string originalTypeName,
        IMethodSymbol constructor, List<FieldPair> members, string source)
    {
        var arguments = constructor.Parameters.Select(parameter =>
        {
            var member = members.First(field => MatchesParameter(field, parameter));
            return ConvertToOriginal(member.Type, $"{source}.@{member.VariableName}");
        });
        code.WriteLine($"return new {originalTypeName}({string.Join(", ", arguments)})");
        code.WriteLine("{");
        code.Indent++;
        foreach (var member in members)
        {
            if (!constructor.Parameters.Any(parameter => MatchesParameter(member, parameter)))
                code.WriteLine($"@{member.VariableName} = {ConvertToOriginal(member.Type, $"{source}.@{member.VariableName}")},");
        }

        code.Indent--;
        code.WriteLine("};");
    }

    private readonly struct FieldPair(ITypeSymbol type, ISymbol symbol)
    {
        public readonly ITypeSymbol Type = type;
        public readonly ISymbol Symbol = symbol;
        public string TypeName
        {
            get
            {
                TryGetSerializedType(Type, out var name);
                return name;
            }
        }
        public string VariableName => Symbol.Name;
    }

    private static bool HasSerdeAttribute(ITypeSymbol type) => type.GetAttributes().Any(attribute =>
        attribute.AttributeClass?.ToDisplayString() == "SerializableGenerator." + k_AttrName);

    private static readonly SymbolDisplayFormat s_TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
                                  SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static bool ContainsSerdeType(ITypeSymbol type) => HasSerdeAttribute(type) || type switch
    {
        IArrayTypeSymbol array => ContainsSerdeType(array.ElementType),
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsSerdeType),
        _ => false
    };

    private static bool IsList(INamedTypeSymbol type) =>
        type.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.List<T>";

    // Descend through containers; every attributed type has its own generator invocation.
    private static bool TryGetSerializedType(ITypeSymbol type, out string name)
    {
        name = type.ToDisplayString(s_TypeFormat);
        if (!ContainsSerdeType(type)) return true;

        if (HasSerdeAttribute(type))
        {
            if (type is not INamedTypeSymbol { Arity: 0, ContainingType: null }) return false;
            var prefix = type.ContainingNamespace.IsGlobalNamespace
                ? "global::"
                : $"global::{type.ContainingNamespace.ToDisplayString()}.";
            name = prefix + k_GenTypePrefix + type.Name;
            if (type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated)
                name += "?";
            return true;
        }

        if (type is IArrayTypeSymbol { Rank: 1, IsSZArray: true } array &&
            TryGetSerializedType(array.ElementType, out var elementName))
        {
            name = elementName + "[]" + NullableSuffix(type);
            return true;
        }

        if (type is INamedTypeSymbol named && named.TypeArguments.Length == 1 &&
            TryGetSerializedType(named.TypeArguments[0], out var argumentName))
        {
            if (named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                name = argumentName + "?";
                return true;
            }
            if (IsList(named))
            {
                name = $"global::System.Collections.Generic.List<{argumentName}>" + NullableSuffix(type);
                return true;
            }
        }

        // Arbitrary generic containers cannot be reconstructed by replacing type arguments alone.
        return false;
    }

    private static string NullableSuffix(ITypeSymbol type) =>
        type.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "";

    private static string ConvertToOriginal(ITypeSymbol type, string expression, int depth = 0)
    {
        if (!ContainsSerdeType(type)) return expression;
        if (HasSerdeAttribute(type))
            return expression + (type.IsReferenceType &&
                                 type.NullableAnnotation == NullableAnnotation.Annotated
                ? "?.ToOriginal()"
                : ".ToOriginal()");

        if (type is INamedTypeSymbol nullable &&
            nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            return $"({expression}.HasValue ? ({type.ToDisplayString(s_TypeFormat)})" +
                   ConvertToOriginal(nullable.TypeArguments[0], expression + ".Value", depth) + " : null)";

        var item = "__item" + depth;
        var elementType = type is IArrayTypeSymbol array
            ? array.ElementType
            : ((INamedTypeSymbol)type).TypeArguments[0];
        var select = $"global::System.Linq.Enumerable.Select({expression}, {item} => " +
                     ConvertToOriginal(elementType, item, depth + 1) + ")";
        var method = type is IArrayTypeSymbol ? "ToArray" : "ToList";
        var materialized = $"global::System.Linq.Enumerable.{method}({select})";
        return $"({expression} is null ? null{(NullableSuffix(type) == "" ? "!" : "")} : {materialized})";
    }

    // Direct recursive struct fields (including Nullable<T>) have infinite size.
    // Arrays and lists introduce indirection and therefore terminate this layout check.
    private static bool HasValueCycle(ITypeSymbol type, HashSet<ITypeSymbol> path)
    {
        if (type is INamedTypeSymbol nullable &&
            nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            return HasValueCycle(nullable.TypeArguments[0], path);
        if (type is not INamedTypeSymbol named || !HasSerdeAttribute(type)) return false;
        if (!path.Add(type)) return true;
        var result = GetFields(named).Any(member => HasValueCycle(member.Type, path));
        path.Remove(type);
        return result;
    }

    private static List<FieldPair> GetFields(INamedTypeSymbol symbol)
    {
        var buffer = new List<FieldPair>(symbol.GetMembers().Length);
        foreach (var member in symbol.GetMembers())
        {
            switch (member)
            {
                case IFieldSymbol { IsStatic: false, IsImplicitlyDeclared: false } field:
                {
                    buffer.Add(new FieldPair(field.Type, field));
                    break;
                }

                case IPropertySymbol { IsStatic: false, IsImplicitlyDeclared: false, IsIndexer: false } property
                    when property.ExplicitInterfaceImplementations.IsEmpty:
                {
                    buffer.Add(new FieldPair(property.Type, property));
                    break;
                }
            }
        }

        return buffer;
    }


    private const string k_AttrName = "SerdeTypeAttribute";
    private const string k_GenTypePrefix = "S_";

    private static readonly DiagnosticDescriptor s_ConversionError = new(
        "SERDE001", "Cannot generate conversion",
        "Cannot generate ToOriginal for '{0}'. Use a non-abstract, non-generic, top-level type with a matching constructor and writable members; declare the type partial to access private members.",
        "SerializableGenerator", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor s_UnsupportedMemberError = new(
        "SERDE002", "Unsupported serialized member",
        "Member '{0}' has unsupported type '{1}'. Serde types can be used directly, in one-dimensional arrays, List<T>, or Nullable<T>.",
        "SerializableGenerator", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor s_RecursiveLayoutError = new(
        "SERDE003", "Recursive serialized struct layout",
        "Type '{0}' contains a direct Serde type cycle. Use an array or List<T> to introduce indirection between generated structs.",
        "SerializableGenerator", DiagnosticSeverity.Error, true);

    private const string k_AttrImpl = """
                                      // <auto-generated/>

                                      using System.Globalization;

                                      namespace SerializableGenerator
                                      {
                                          [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false)]
                                          internal sealed class SerdeTypeAttribute : global::System.Attribute { }
                                      }
                                      """;
}
